FROM mysql:8.0

# Set environment variables for MySQL root password and database name
ENV MYSQL_ROOT_PASSWORD=legalease
ENV MYSQL_DATABASE=legalease
ENV MYSQL_USER=legalease
ENV MYSQL_PASSWORD=legalease

# Expose the MySQL port
EXPOSE 3306
